import TomographyOracleCore.BinaryCliffordTransvection
import TomographyOracleCore.CliffordPauliCounting

namespace TomographyOracleCore

/-!
# Finite transvection-generated Clifford ensemble

We generate a finite subgroup of the binary symplectic group using all
symplectic transvections.  The generators are involutions, so their monoid
closure is already closed under inverses.  This formulation lets unitary
lifts be propagated using only identity and multiplication.
-/

/-- All binary symplectic transvections, viewed inside the finite
symplectic group. -/
def binaryTransvectionGeneratorSet (K : ℕ) :
    Set (binarySymplecticGroup K) :=
  Set.range (binarySymplecticTransvection K)

/-- Monoid generated by all binary symplectic transvections. -/
def binaryTransvectionSubmonoid (K : ℕ) :
    Submonoid (binarySymplecticGroup K) :=
  Submonoid.closure (binaryTransvectionGeneratorSet K)

/-- Every transvection generator is its own inverse. -/
theorem binarySymplecticTransvection_inv (K : ℕ) (a : PauliLabel K) :
    (binarySymplecticTransvection K a)⁻¹ =
      binarySymplecticTransvection K a := by
  apply inv_eq_of_mul_eq_one_left
  apply Subtype.ext
  apply LinearEquiv.ext
  intro p
  change pauliTransvection K a (pauliTransvection K a p) = p
  exact pauliTransvectionLinear_involutive K a p

/-- Because the generators are involutions, the transvection monoid closure
is closed under ambient group inversion. -/
theorem binaryTransvectionSubmonoid_inv_mem (K : ℕ)
    {g : binarySymplecticGroup K}
    (hg : g ∈ binaryTransvectionSubmonoid K) :
    g⁻¹ ∈ binaryTransvectionSubmonoid K := by
  change g⁻¹ ∈ Submonoid.closure (binaryTransvectionGeneratorSet K)
  change g ∈ Submonoid.closure (binaryTransvectionGeneratorSet K) at hg
  refine Submonoid.closure_induction
    (motive := fun x _ ↦
      x⁻¹ ∈ Submonoid.closure (binaryTransvectionGeneratorSet K))
    ?_ ?_ ?_ hg
  · intro x hx
    obtain ⟨a, rfl⟩ := hx
    rw [binarySymplecticTransvection_inv]
    exact Submonoid.subset_closure ⟨a, rfl⟩
  · simp
  · intro x y _ _ hx hy
    rw [mul_inv_rev]
    exact (Submonoid.closure (binaryTransvectionGeneratorSet K)).mul_mem hy hx

/-- Finite subgroup generated by all binary symplectic transvections. -/
def binaryTransvectionGroup (K : ℕ) :
    Subgroup (binarySymplecticGroup K) where
  carrier := binaryTransvectionSubmonoid K
  one_mem' := (binaryTransvectionSubmonoid K).one_mem
  mul_mem' := (binaryTransvectionSubmonoid K).mul_mem
  inv_mem' := binaryTransvectionSubmonoid_inv_mem K

noncomputable instance binaryTransvectionGroupFintype (K : ℕ) :
    Fintype (binaryTransvectionGroup K) :=
  Fintype.ofFinite _

/-- Natural action of the generated subgroup on Pauli labels. -/
instance binaryTransvectionGroupMulAction (K : ℕ) :
    MulAction (binaryTransvectionGroup K) (PauliLabel K) :=
  MulAction.compHom (PauliLabel K) (binaryTransvectionGroup K).subtype

@[simp] theorem binaryTransvectionGroup_smul_apply (K : ℕ)
    (g : binaryTransvectionGroup K) (p : PauliLabel K) :
    g • p = g.1.1 p := rfl

/-- Natural action on nonidentity Pauli labels. -/
instance binaryTransvectionGroupNonidentityMulAction (K : ℕ) :
    MulAction (binaryTransvectionGroup K) (NonidentityPauliLabel K) where
  smul g p := ⟨g.1.1 p.1, by
    intro h
    apply p.2
    apply g.1.1.injective
    simpa using h⟩
  one_smul p := by apply Subtype.ext; rfl
  mul_smul g h p := by apply Subtype.ext; rfl

/-- Every transvection generator belongs to the generated subgroup. -/
noncomputable def binaryTransvectionGenerator (K : ℕ)
    (a : PauliLabel K) : binaryTransvectionGroup K :=
  ⟨binarySymplecticTransvection K a,
    Submonoid.subset_closure ⟨a, rfl⟩⟩

/-- The generated subgroup remains transitive on all nonidentity Pauli
labels; the same two explicit transvections suffice. -/
theorem binaryTransvectionGroup_exists_smul_eq (K : ℕ)
    (p q : NonidentityPauliLabel K) :
    ∃ g : binaryTransvectionGroup K, g • p = q := by
  obtain ⟨a, hpa, hqa⟩ :=
    exists_common_pauliSymplectic_pair_one K p.2 q.2
  have haq : pauliSymplecticForm K a q.1 = 1 := by
    rw [pauliSymplecticForm_symm]
    exact hqa
  let g₁ := binaryTransvectionGenerator K (p.1 + a)
  let g₂ := binaryTransvectionGenerator K (a + q.1)
  refine ⟨g₂ * g₁, ?_⟩
  apply Subtype.ext
  change pauliTransvection K (a + q.1)
      (pauliTransvection K (p.1 + a) p.1) = q.1
  rw [pauliTransvection_add_map_of_pair_one K hpa,
    pauliTransvection_add_map_of_pair_one K haq]

instance binaryTransvectionGroup_isPretransitive (K : ℕ) :
    MulAction.IsPretransitive (binaryTransvectionGroup K)
      (NonidentityPauliLabel K) where
  exists_smul_eq p q := binaryTransvectionGroup_exists_smul_eq K p q

/-- Exact local Z-hit probability for the smaller, concretely liftable
transvection-generated Clifford ensemble. -/
theorem uniform_binaryTransvectionGroup_z_probability
    {K : ℕ} (hK : 0 < K) (Q : NonidentityPauliLabel K) :
    ((Fintype.card
        {c : binaryTransvectionGroup K // (c • Q).1.1 = 0} : ℕ) : ℝ) /
        Fintype.card (binaryTransvectionGroup K) =
      1 / ((2 : ℝ) ^ K + 1) :=
  uniform_transitive_pauli_action_z_probability hK Q

/-! ## Unitary lifts propagated through the generated subgroup -/

/-- `U` implements the binary symplectic label action `g` on every concrete
Pauli matrix, allowing the unavoidable nonzero complex phase. -/
def IsUnitaryPauliLift (K : ℕ) (g : binarySymplecticGroup K)
    (U : Matrix.unitaryGroup (PauliBinaryWord K) ℂ) : Prop :=
  ∀ p : PauliLabel K, ∃ phase : ℂ, phase ≠ 0 ∧
    ((U.1 * binaryPauliMatrix K p) * U.1.conjTranspose) =
      phase • binaryPauliMatrix K (g.1 p)

/-- Existence of a concrete unitary Pauli lift. -/
def HasUnitaryPauliLift (K : ℕ) (g : binarySymplecticGroup K) : Prop :=
  ∃ U : Matrix.unitaryGroup (PauliBinaryWord K) ℂ,
    IsUnitaryPauliLift K g U

/-- Every generating transvection has the explicit unitary lift constructed
in `BinaryCliffordTransvection`. -/
theorem binaryTransvectionGenerator_hasUnitaryPauliLift (K : ℕ)
    (a : PauliLabel K) :
    HasUnitaryPauliLift K (binarySymplecticTransvection K a) := by
  refine ⟨cliffordTransvectionUnitary K a, ?_⟩
  intro p
  exact cliffordTransvectionMatrix_conjugates_pauli K a p

/-- The identity symplectic action is lifted by the identity unitary. -/
theorem one_hasUnitaryPauliLift (K : ℕ) :
    HasUnitaryPauliLift K 1 := by
  refine ⟨1, ?_⟩
  intro p
  refine ⟨1, one_ne_zero, ?_⟩
  simp [Matrix.conjTranspose_one]

/-- Products of liftable symplectic actions are lifted by products of their
unitaries. -/
theorem HasUnitaryPauliLift.mul (K : ℕ)
    {g h : binarySymplecticGroup K}
    (hg : HasUnitaryPauliLift K g)
    (hh : HasUnitaryPauliLift K h) :
    HasUnitaryPauliLift K (g * h) := by
  obtain ⟨U, hU⟩ := hg
  obtain ⟨V, hV⟩ := hh
  refine ⟨U * V, ?_⟩
  intro p
  obtain ⟨c, hc, hVc⟩ := hV p
  obtain ⟨d, hd, hUd⟩ := hU (h.1 p)
  refine ⟨c * d, mul_ne_zero hc hd, ?_⟩
  change (((U.1 * V.1) * binaryPauliMatrix K p) *
      (U.1 * V.1).conjTranspose) =
    (c * d) • binaryPauliMatrix K (g.1 (h.1 p))
  rw [Matrix.conjTranspose_mul]
  calc
    ((U.1 * V.1) * binaryPauliMatrix K p) *
          (V.1.conjTranspose * U.1.conjTranspose) =
        (U.1 * ((V.1 * binaryPauliMatrix K p) *
          V.1.conjTranspose)) * U.1.conjTranspose := by
      noncomm_ring
    _ = (U.1 * (c • binaryPauliMatrix K (h.1 p))) *
          U.1.conjTranspose := by rw [hVc]
    _ = c • ((U.1 * binaryPauliMatrix K (h.1 p)) *
          U.1.conjTranspose) := by
      rw [Matrix.mul_smul, Matrix.smul_mul]
    _ = c • (d • binaryPauliMatrix K (g.1 (h.1 p))) := by
      rw [hUd]
    _ = (c * d) • binaryPauliMatrix K (g.1 (h.1 p)) := by
      rw [smul_smul]

/-- Every element of the transvection monoid closure has a concrete unitary
Pauli lift.  Only generator, identity, and product cases are needed. -/
theorem binaryTransvectionSubmonoid_hasUnitaryPauliLift (K : ℕ)
    {g : binarySymplecticGroup K}
    (hg : g ∈ binaryTransvectionSubmonoid K) :
    HasUnitaryPauliLift K g := by
  change g ∈ Submonoid.closure (binaryTransvectionGeneratorSet K) at hg
  refine Submonoid.closure_induction
    (motive := fun x _ ↦ HasUnitaryPauliLift K x)
    ?_ (one_hasUnitaryPauliLift K) ?_ hg
  · intro x hx
    obtain ⟨a, rfl⟩ := hx
    exact binaryTransvectionGenerator_hasUnitaryPauliLift K a
  · intro x y _ _ hx hy
    exact hx.mul K hy

/-- Every element of the finite generated subgroup has a concrete unitary
Pauli lift. -/
theorem binaryTransvectionGroup_hasUnitaryPauliLift (K : ℕ)
    (g : binaryTransvectionGroup K) :
    HasUnitaryPauliLift K g.1 :=
  binaryTransvectionSubmonoid_hasUnitaryPauliLift K g.2

/-- Choose one concrete unitary lift for every element of the finite
transvection-generated group. -/
noncomputable def binaryTransvectionUnitaryLift (K : ℕ)
    (g : binaryTransvectionGroup K) :
    Matrix.unitaryGroup (PauliBinaryWord K) ℂ :=
  Classical.choose (binaryTransvectionGroup_hasUnitaryPauliLift K g)

/-- The chosen unitary implements its symplectic label action on every
Pauli, up to nonzero phase. -/
theorem binaryTransvectionUnitaryLift_spec (K : ℕ)
    (g : binaryTransvectionGroup K) :
    IsUnitaryPauliLift K g.1 (binaryTransvectionUnitaryLift K g) :=
  Classical.choose_spec (binaryTransvectionGroup_hasUnitaryPauliLift K g)

end TomographyOracleCore
