import TomographyOracleCore.BinaryCliffordGeneratedEnsemble
import Mathlib.LinearAlgebra.BilinearForm.Properties
import Mathlib.LinearAlgebra.Basis.VectorSpace

namespace TomographyOracleCore

/-!
# Pauli two-mixing for the generated Clifford ensemble

An exact Clifford three-design needs more than transitivity on individual
nonidentity Pauli labels.  The label-level input is transitivity on ordered
pairs of distinct nonidentity labels with a fixed symplectic product
(equivalently, a fixed commutation sign).

This module proves that stronger finite-group statement constructively for
the subgroup generated by binary symplectic transvections.
-/

/-- The canonical Pauli symplectic form is nondegenerate. -/
theorem pauliSymplecticForm_nondegenerate (K : ℕ) :
    (pauliSymplecticForm K).Nondegenerate := by
  apply LinearMap.BilinForm.Nondegenerate.ofSeparatingLeft
  intro p hp
  by_contra hp0
  obtain ⟨q, hpq⟩ := exists_pauliSymplectic_pair_one K hp0
  have hz := hp q
  rw [hpq] at hz
  exact one_ne_zero hz

/-- Over the binary field, a vector outside the four possibilities
`0, q, r, q+r` is not in the span of `q,r`. -/
theorem not_mem_span_pair_of_binary
    (K : ℕ) {p q r : PauliLabel K}
    (hp : p ≠ 0) (hpq : p ≠ q) (hpr : p ≠ r)
    (hpqr : p ≠ q + r) :
    p ∉ Submodule.span (ZMod 2) ({q, r} : Set (PauliLabel K)) := by
  intro hspan
  rw [Submodule.mem_span_pair] at hspan
  obtain ⟨a, b, hab⟩ := hspan
  rcases zmodTwo_eq_zero_or_one a with rfl | rfl <;>
    rcases zmodTwo_eq_zero_or_one b with rfl | rfl
  · simp at hab
    exact hp hab.symm
  · simp at hab
    exact hpr hab.symm
  · simp at hab
    exact hpq hab.symm
  · simp at hab
    exact hpqr hab.symm

/-- If `p` lies outside the span of `q,r`, nondegeneracy supplies a vector
pairing to one with `p` and to zero with both `q` and `r`. -/
theorem exists_pauliSymplectic_one_zero_zero_of_not_mem_span
    (K : ℕ) {p q r : PauliLabel K}
    (hp : p ∉ Submodule.span (ZMod 2) ({q, r} : Set (PauliLabel K))) :
    ∃ b : PauliLabel K,
      pauliSymplecticForm K p b = 1 ∧
      pauliSymplecticForm K q b = 0 ∧
      pauliSymplecticForm K r b = 0 := by
  let W : Submodule (ZMod 2) (PauliLabel K) :=
    Submodule.span (ZMod 2) ({q, r} : Set (PauliLabel K))
  obtain ⟨f, hfW, hfp⟩ :=
    LinearMap.exists_extend_of_notMem
      (p := W) (0 : W →ₗ[ZMod 2] ZMod 2) hp 1
  let b : PauliLabel K :=
    ((pauliSymplecticForm K).toDual
      (pauliSymplecticForm_nondegenerate K)).symm f
  have hpair (v : PauliLabel K) :
      pauliSymplecticForm K v b = f v := by
    rw [pauliSymplecticForm_symm]
    exact LinearMap.BilinForm.apply_toDual_symm_apply f v
  refine ⟨b, ?_, ?_, ?_⟩
  · rw [hpair, hfp]
  · rw [hpair]
    have hqW : q ∈ W := Submodule.subset_span (by simp [W])
    have hq := LinearMap.congr_fun hfW (⟨q, hqW⟩ : W)
    simpa using hq
  · rw [hpair]
    have hrW : r ∈ W := Submodule.subset_span (by simp [W])
    have hr := LinearMap.congr_fun hfW (⟨r, hrW⟩ : W)
    simpa using hr

/-- Three pairwise-orthogonal, suitable nonzero labels have an intermediate
label orthogonal to `p` and pairing to one with both `q` and `r`. -/
theorem exists_pauliSymplectic_common_one_orthogonal
    (K : ℕ) {p q r : PauliLabel K}
    (hp : p ≠ 0) (hq : q ≠ 0) (hr : r ≠ 0)
    (hpq_ne : p ≠ q) (hpr_ne : p ≠ r)
    (hpq : pauliSymplecticForm K p q = 0)
    (hpr : pauliSymplecticForm K p r = 0)
    (hqr : pauliSymplecticForm K q r = 0) :
    ∃ a : PauliLabel K,
      pauliSymplecticForm K p a = 0 ∧
      pauliSymplecticForm K q a = 1 ∧
      pauliSymplecticForm K r a = 1 := by
  obtain ⟨a, hqa, hra⟩ :=
    exists_common_pauliSymplectic_pair_one K hq hr
  by_cases hpa : pauliSymplecticForm K p a = 0
  · exact ⟨a, hpa, hqa, hra⟩
  · have hpa1 : pauliSymplecticForm K p a = 1 := by
      rcases zmodTwo_eq_zero_or_one (pauliSymplecticForm K p a) with h | h
      · exact (hpa h).elim
      · exact h
    have hpqr : p ≠ q + r := by
      intro heq
      have : pauliSymplecticForm K p a = 0 := by
        rw [heq, map_add, LinearMap.add_apply, hqa, hra]
        exact CharTwo.add_self_eq_zero 1
      exact hpa this
    have hpSpan := not_mem_span_pair_of_binary K hp hpq_ne hpr_ne hpqr
    obtain ⟨b, hpb, hqb, hrb⟩ :=
      exists_pauliSymplectic_one_zero_zero_of_not_mem_span K hpSpan
    refine ⟨a + b, ?_, ?_, ?_⟩
    · rw [map_add, hpa1, hpb]
      exact CharTwo.add_self_eq_zero 1
    · rw [map_add, hqa, hqb, add_zero]
    · rw [map_add, hra, hrb, add_zero]

/-- A transvection fixes any vector orthogonal to its direction. -/
theorem pauliTransvection_fix_of_pair_zero
    (K : ℕ) {a p : PauliLabel K}
    (hpa : pauliSymplecticForm K p a = 0) :
    pauliTransvection K a p = p := by
  rw [pauliTransvection_apply, hpa, zero_smul, add_zero]

/-- Stabilizer transitivity: while fixing a nonzero label `p`, generated
transvections can map `q` to `r` whenever both are distinct from `p` and
have the same symplectic product with `p`. -/
theorem binaryTransvectionGroup_exists_fix_and_map
    (K : ℕ) {p q r : PauliLabel K}
    (hp : p ≠ 0) (hq : q ≠ 0) (hr : r ≠ 0)
    (hqp : q ≠ p) (hrp : r ≠ p)
    (hform : pauliSymplecticForm K p q =
      pauliSymplecticForm K p r) :
    ∃ g : binaryTransvectionGroup K,
      g.1.1 p = p ∧ g.1.1 q = r := by
  by_cases hqr_eq : q = r
  · subst r
    exact ⟨1, by simp, by simp⟩
  rcases zmodTwo_eq_zero_or_one (pauliSymplecticForm K q r) with hqr | hqr
  · rcases zmodTwo_eq_zero_or_one (pauliSymplecticForm K p q) with hpq | hpq
    · have hpr : pauliSymplecticForm K p r = 0 := by
        rw [← hform, hpq]
      obtain ⟨a, hpa, hqa, hra⟩ :=
        exists_pauliSymplectic_common_one_orthogonal K hp hq hr
          (Ne.symm hqp) (Ne.symm hrp) hpq hpr hqr
      let g₁ := binaryTransvectionGenerator K (q + a)
      let g₂ := binaryTransvectionGenerator K (a + r)
      refine ⟨g₂ * g₁, ?_, ?_⟩
      · change pauliTransvection K (a + r)
          (pauliTransvection K (q + a) p) = p
        have hpqa : pauliSymplecticForm K p (q + a) = 0 := by
          rw [map_add, hpq, hpa, zero_add]
        have hpar : pauliSymplecticForm K p (a + r) = 0 := by
          rw [map_add, hpa, hpr, zero_add]
        rw [pauliTransvection_fix_of_pair_zero K hpqa,
          pauliTransvection_fix_of_pair_zero K hpar]
      · change pauliTransvection K (a + r)
          (pauliTransvection K (q + a) q) = r
        have har : pauliSymplecticForm K a r = 1 := by
          rw [pauliSymplecticForm_symm]
          exact hra
        rw [pauliTransvection_add_map_of_pair_one K hqa,
          pauliTransvection_add_map_of_pair_one K har]
    · have hpr : pauliSymplecticForm K p r = 1 := by
        rw [← hform, hpq]
      let a := q + p
      let g₁ := binaryTransvectionGenerator K p
      let g₂ := binaryTransvectionGenerator K (a + r)
      have hqa : pauliSymplecticForm K q a = 1 := by
        change pauliSymplecticForm K q (q + p) = 1
        rw [map_add, pauliSymplecticForm_self, pauliSymplecticForm_symm,
          hpq, zero_add]
      have har : pauliSymplecticForm K a r = 1 := by
        change pauliSymplecticForm K (q + p) r = 1
        rw [map_add, LinearMap.add_apply, hqr, hpr, zero_add]
      have hpa : pauliSymplecticForm K p a = 1 := by
        change pauliSymplecticForm K p (q + p) = 1
        rw [map_add, hpq, pauliSymplecticForm_self, add_zero]
      have hpar : pauliSymplecticForm K p (a + r) = 0 := by
        rw [map_add, hpa, hpr]
        exact CharTwo.add_self_eq_zero 1
      refine ⟨g₂ * g₁, ?_, ?_⟩
      · change pauliTransvection K (a + r)
          (pauliTransvection K p p) = p
        rw [pauliTransvection_fix_of_pair_zero K
            (pauliSymplecticForm_self K p),
          pauliTransvection_fix_of_pair_zero K hpar]
      · change pauliTransvection K (a + r)
          (pauliTransvection K p q) = r
        have hqp1 : pauliSymplecticForm K q p = 1 := by
          rw [pauliSymplecticForm_symm, hpq]
        rw [show pauliTransvection K p q = a by
          rw [pauliTransvection_apply, hqp1, one_smul],
          pauliTransvection_add_map_of_pair_one K har]
  · let g := binaryTransvectionGenerator K (q + r)
    have hpdir : pauliSymplecticForm K p (q + r) = 0 := by
      rw [map_add, hform]
      exact CharTwo.add_self_eq_zero _
    refine ⟨g, ?_, ?_⟩
    · exact pauliTransvection_fix_of_pair_zero K hpdir
    · exact pauliTransvection_add_map_of_pair_one K hqr

/-- Ordered-pair transitivity for the generated symplectic subgroup.  The
only invariant is the symplectic product (the Pauli commutation sign). -/
theorem binaryTransvectionGroup_exists_map_ordered_pair
    (K : ℕ) {p q p' q' : PauliLabel K}
    (hp : p ≠ 0) (hq : q ≠ 0) (hp' : p' ≠ 0) (hq' : q' ≠ 0)
    (hpq : p ≠ q) (hpq' : p' ≠ q')
    (hform : pauliSymplecticForm K p q =
      pauliSymplecticForm K p' q') :
    ∃ g : binaryTransvectionGroup K,
      g.1.1 p = p' ∧ g.1.1 q = q' := by
  obtain ⟨g₀, hg₀⟩ := binaryTransvectionGroup_exists_smul_eq K
    (⟨p, hp⟩ : NonidentityPauliLabel K)
    (⟨p', hp'⟩ : NonidentityPauliLabel K)
  have hg₀p : g₀.1.1 p = p' := congrArg Subtype.val hg₀
  let r : PauliLabel K := g₀.1.1 q
  have hr : r ≠ 0 := by
    intro hr0
    apply hq
    apply g₀.1.1.injective
    simpa [r] using hr0
  have hrp' : r ≠ p' := by
    intro heq
    apply hpq
    apply g₀.1.1.injective
    rw [hg₀p]
    exact heq.symm
  have hrform : pauliSymplecticForm K p' r =
      pauliSymplecticForm K p' q' := by
    calc
      pauliSymplecticForm K p' r =
          pauliSymplecticForm K (g₀.1.1 p) (g₀.1.1 q) := by
            rw [hg₀p]
      _ = pauliSymplecticForm K p q := g₀.1.2 p q
      _ = pauliSymplecticForm K p' q' := hform
  obtain ⟨h, hfix, hmap⟩ :=
    binaryTransvectionGroup_exists_fix_and_map K hp' hr hq'
      hrp' (Ne.symm hpq') hrform
  refine ⟨h * g₀, ?_, ?_⟩
  · change h.1.1 (g₀.1.1 p) = p'
    rw [hg₀p, hfix]
  · change h.1.1 (g₀.1.1 q) = q'
    exact hmap

/-- Ordered distinct nonidentity Pauli pairs with fixed commutation sign. -/
def PauliPairClass (K : ℕ) (c : ZMod 2) :=
  {pq : PauliLabel K × PauliLabel K //
    pq.1 ≠ 0 ∧ pq.2 ≠ 0 ∧ pq.1 ≠ pq.2 ∧
      pauliSymplecticForm K pq.1 pq.2 = c}

noncomputable instance pauliPairClassFintype (K : ℕ) (c : ZMod 2) :
    Fintype (PauliPairClass K c) :=
  Fintype.ofInjective
    (fun x : PauliPairClass K c ↦ x.1)
    (fun _ _ h ↦ Subtype.ext h)

/-- Componentwise action of the generated Clifford quotient on a fixed
Pauli-pair commutation class. -/
instance pauliPairClassMulAction (K : ℕ) (c : ZMod 2) :
    MulAction (binaryTransvectionGroup K) (PauliPairClass K c) where
  smul g x := ⟨(g.1.1 x.1.1, g.1.1 x.1.2), by
    refine ⟨?_, ?_, ?_, ?_⟩
    · intro hz
      exact x.2.1 (g.1.1.injective (by simpa using hz))
    · intro hz
      exact x.2.2.1 (g.1.1.injective (by simpa using hz))
    · intro heq
      exact x.2.2.2.1 (g.1.1.injective heq)
    · exact (g.1.2 x.1.1 x.1.2).trans x.2.2.2.2⟩
  one_smul x := by apply Subtype.ext; rfl
  mul_smul g h x := by apply Subtype.ext; rfl

/-- The generated Clifford quotient is Pauli 2-mixing: it acts transitively
on every fixed commutation class of ordered distinct nonidentity pairs. -/
instance binaryTransvectionGroup_pauliPairClass_isPretransitive
    (K : ℕ) (c : ZMod 2) :
    MulAction.IsPretransitive (binaryTransvectionGroup K)
      (PauliPairClass K c) where
  exists_smul_eq x y := by
    obtain ⟨g, hp, hq⟩ :=
      binaryTransvectionGroup_exists_map_ordered_pair K
        x.2.1 x.2.2.1 y.2.1 y.2.2.1
        x.2.2.2.1 y.2.2.2.1
        (x.2.2.2.2.trans y.2.2.2.2.symm)
    refine ⟨g, ?_⟩
    apply Subtype.ext
    exact Prod.ext hp hq

end TomographyOracleCore
