import TomographyOracleCore.Structural

namespace TomographyOracleCore

/-!
The class-specific part of the fixed-design upper bound.

This file starts from a *semantic expected oracle*: for every state in the
class, its expected trace error obeys `OracleBound` simultaneously at every
integer truncation level.  It proves the integer rounding and the two endpoint
regimes, then passes from the risk of the exhibited estimator to the infimum
over estimators.  No statement below assumes the target upper inequality.
-/

/-- The three-regime decay-class rate generated by a noise level `eta`:
the deterministic loss cap, the polynomial-tail balance, and the full-rank
endpoint. -/
noncomputable def decayUpperRate
    (D : ℕ) (L eta alpha : ℝ) : ℝ :=
  min 1 (min (L ^ alpha⁻¹ * eta ^ ((alpha - 1) / alpha))
    (eta * (D : ℝ)))

/-- The same rate after substituting the tomography noise scale
`eta = sqrt (D / T)`. -/
noncomputable def samplingDecayRate
    (D : ℕ) (T L alpha : ℝ) : ℝ :=
  min 1 (min
    (L ^ alpha⁻¹ *
      ((D : ℝ) / T) ^ ((alpha - 1) / (2 * alpha)))
    (Real.sqrt ((D : ℝ) ^ 3 / T)))

/-- The full-rank endpoint `D * sqrt(D/T)` is exactly
`sqrt(D^3/T)`. -/
theorem sqrt_dimension_noise_eq_full_rank
    (D : ℕ) (T : ℝ) (hT : 0 < T) :
    Real.sqrt ((D : ℝ) / T) * (D : ℝ) =
      Real.sqrt ((D : ℝ) ^ 3 / T) := by
  have hD0 : 0 ≤ (D : ℝ) := Nat.cast_nonneg D
  have hquot : 0 ≤ (D : ℝ) / T := div_nonneg hD0 hT.le
  have hcubic : 0 ≤ (D : ℝ) ^ 3 / T :=
    div_nonneg (pow_nonneg hD0 3) hT.le
  apply (mul_self_inj_of_nonneg
    (mul_nonneg (Real.sqrt_nonneg _) hD0) (Real.sqrt_nonneg _)).mp
  calc
    (Real.sqrt ((D : ℝ) / T) * (D : ℝ)) *
        (Real.sqrt ((D : ℝ) / T) * (D : ℝ))
        = (Real.sqrt ((D : ℝ) / T)) ^ 2 * (D : ℝ) ^ 2 := by ring
    _ = ((D : ℝ) / T) * (D : ℝ) ^ 2 := by
      rw [Real.sq_sqrt hquot]
    _ = (D : ℝ) ^ 3 / T := by ring
    _ = (Real.sqrt ((D : ℝ) ^ 3 / T)) ^ 2 := by
      rw [Real.sq_sqrt hcubic]
    _ = Real.sqrt ((D : ℝ) ^ 3 / T) *
        Real.sqrt ((D : ℝ) ^ 3 / T) := by ring

/-- Algebraic identification of the abstract-`eta` rate with the advertised
`D,T` sampling rate. -/
theorem decayUpperRate_sqrt_dimension_div_samples
    (D : ℕ) (T L alpha : ℝ) (hT : 0 < T) (halpha0 : alpha ≠ 0) :
    decayUpperRate D L (Real.sqrt ((D : ℝ) / T)) alpha =
      samplingDecayRate D T L alpha := by
  have hquot : 0 ≤ (D : ℝ) / T :=
    div_nonneg (Nat.cast_nonneg D) hT.le
  have hpow :
      (Real.sqrt ((D : ℝ) / T)) ^ ((alpha - 1) / alpha) =
      ((D : ℝ) / T) ^ ((alpha - 1) / (2 * alpha)) := by
    rw [Real.sqrt_eq_rpow]
    rw [← Real.rpow_mul hquot]
    congr 1
    field_simp
  simp only [decayUpperRate, samplingDecayRate, hpow,
    sqrt_dimension_noise_eq_full_rank D T hT]

/-- Integer rounding at the continuous balanced scale.  In the interior
regime `1 ≤ u ≤ D`, choosing `s = ceil u` loses at most the explicit constant
`12`, where `u = balancedScale L eta beta` and the oracle noise is `4 * eta`.
-/
theorem decay_oracle_interior_beta
    (err L eta beta : ℝ) (tail : ℕ → ℝ) (D : ℕ)
    (hL : 0 < L) (heta : 0 < eta)
    (hbeta0 : 0 < beta) (hbeta1 : beta < 1)
    (hu1 : 1 ≤ balancedScale L eta beta)
    (huD : balancedScale L eta beta ≤ (D : ℝ))
    (horacle : OracleBound err tail (4 * eta) D)
    (htail : ∀ s, 1 ≤ s → s ≤ D →
      tail s ≤ L * (s : ℝ) ^ (1 - beta⁻¹)) :
    err ≤ 12 * polynomialRate L eta beta := by
  let u : ℝ := balancedScale L eta beta
  let s : ℕ := ⌈u⌉₊
  have hu_pos : 0 < u := by
    dsimp [u, balancedScale]
    exact mul_pos (Real.rpow_pos_of_pos hL beta)
      (Real.rpow_pos_of_pos heta (-beta))
  have hs1 : 1 ≤ s := by
    exact (Nat.ceil_pos.mpr hu_pos)
  have hsD : s ≤ D := by
    exact Nat.ceil_le.mpr huD
  have hu_le_s : u ≤ (s : ℝ) := by
    exact Nat.le_ceil u
  have hs_le_two_u : (s : ℝ) ≤ 2 * u := by
    have hs_lt : (s : ℝ) < u + 1 := Nat.ceil_lt_add_one hu_pos.le
    linarith
  have hexp : 1 - beta⁻¹ ≤ 0 := by
    have hone_inv : 1 < beta⁻¹ := (one_lt_inv₀ hbeta0).mpr hbeta1
    linarith
  have hs_pos : 0 < (s : ℝ) := by exact_mod_cast hs1
  have hrpow :
      (s : ℝ) ^ (1 - beta⁻¹) ≤ u ^ (1 - beta⁻¹) :=
    Real.rpow_le_rpow_of_nonpos hu_pos hu_le_s hexp
  have happrox :
      L * (s : ℝ) ^ (1 - beta⁻¹) ≤ polynomialRate L eta beta := by
    calc
      L * (s : ℝ) ^ (1 - beta⁻¹)
          ≤ L * u ^ (1 - beta⁻¹) :=
            mul_le_mul_of_nonneg_left hrpow hL.le
      _ = polynomialRate L eta beta := by
        simpa [u] using
          approximation_at_balanced_scale L eta beta hL heta hbeta0.ne'
  have hest :
      (4 * eta) * (s : ℝ) ≤ 8 * polynomialRate L eta beta := by
    have hscale : eta * u = polynomialRate L eta beta := by
      simpa [u] using estimation_at_balanced_scale L eta beta heta
    calc
      (4 * eta) * (s : ℝ) ≤ (4 * eta) * (2 * u) := by
        exact mul_le_mul_of_nonneg_left hs_le_two_u (by positivity)
      _ = 8 * (eta * u) := by ring
      _ = 8 * polynomialRate L eta beta := by rw [hscale]
  have hraw := horacle s hs1 hsD
  have htail_s := htail s hs1 hsD
  linarith

/-- The polynomial-rate bound is valid globally, not only in the interior.
For `u < 1` it follows from the deterministic loss cap and the fact that the
polynomial rate is at least one; for `D < u` it follows from the full-rank
choice `s = D` and `tail D = 0`. -/
theorem decay_oracle_polynomial_beta
    (err L eta beta : ℝ) (tail : ℕ → ℝ) (D : ℕ)
    (hD : 1 ≤ D) (hL : 1 ≤ L) (heta : 0 < eta)
    (hbeta0 : 0 < beta) (hbeta1 : beta < 1)
    (hcap : err ≤ 2)
    (horacle : OracleBound err tail (4 * eta) D)
    (htail : ∀ s, 1 ≤ s → s ≤ D →
      tail s ≤ L * (s : ℝ) ^ (1 - beta⁻¹))
    (htailD : tail D = 0) :
    err ≤ 12 * polynomialRate L eta beta := by
  let u : ℝ := balancedScale L eta beta
  have hu_pos : 0 < u := by
    dsimp [u, balancedScale]
    exact mul_pos (Real.rpow_pos_of_pos (lt_of_lt_of_le zero_lt_one hL) beta)
      (Real.rpow_pos_of_pos heta (-beta))
  have hexp : 1 - beta⁻¹ ≤ 0 := by
    have hone_inv : 1 < beta⁻¹ := (one_lt_inv₀ hbeta0).mpr hbeta1
    linarith
  by_cases hu1 : 1 ≤ u
  · by_cases huD : u ≤ (D : ℝ)
    · exact decay_oracle_interior_beta err L eta beta tail D
        (lt_of_lt_of_le zero_lt_one hL) heta hbeta0 hbeta1 hu1 huD
        horacle htail
    · have hDu : (D : ℝ) ≤ u := le_of_not_ge huD
      have hfull : err ≤ (4 * eta) * (D : ℝ) := by
        simpa [htailD] using horacle D hD le_rfl
      have hscale : eta * u = polynomialRate L eta beta := by
        simpa [u] using estimation_at_balanced_scale L eta beta heta
      have hDscale : eta * (D : ℝ) ≤ polynomialRate L eta beta := by
        calc
          eta * (D : ℝ) ≤ eta * u :=
            mul_le_mul_of_nonneg_left hDu heta.le
          _ = polynomialRate L eta beta := hscale
      nlinarith
  · have hu_le_one : u ≤ 1 := le_of_not_ge hu1
    have hpow : 1 ≤ u ^ (1 - beta⁻¹) := by
      have := Real.rpow_le_rpow_of_nonpos hu_pos hu_le_one hexp
      simpa using this
    have hrate_one : 1 ≤ polynomialRate L eta beta := by
      have hbalanced :=
        approximation_at_balanced_scale L eta beta
          (lt_of_lt_of_le zero_lt_one hL) heta hbeta0.ne'
      have hLu : 1 ≤ L * u ^ (1 - beta⁻¹) := by nlinarith
      rw [← hbalanced]
      simpa [u] using hLu
    nlinarith

/-- Complete three-regime deterministic decay upper bound.  The three terms
are the loss cap, the polynomial-decay rate, and the full-rank rate. -/
theorem decay_oracle_three_regime_beta
    (err L eta beta : ℝ) (tail : ℕ → ℝ) (D : ℕ)
    (hD : 1 ≤ D) (hL : 1 ≤ L) (heta : 0 < eta)
    (hbeta0 : 0 < beta) (hbeta1 : beta < 1)
    (hcap : err ≤ 2)
    (horacle : OracleBound err tail (4 * eta) D)
    (htail : ∀ s, 1 ≤ s → s ≤ D →
      tail s ≤ L * (s : ℝ) ^ (1 - beta⁻¹))
    (htailD : tail D = 0) :
    err ≤ 12 * min 1
      (min (polynomialRate L eta beta) (eta * (D : ℝ))) := by
  have hpoly := decay_oracle_polynomial_beta err L eta beta tail D hD hL
    heta hbeta0 hbeta1 hcap horacle htail htailD
  have hfull : err ≤ 12 * (eta * (D : ℝ)) := by
    have hraw : err ≤ (4 * eta) * (D : ℝ) := by
      simpa [htailD] using horacle D hD le_rfl
    nlinarith
  have hcap' : err ≤ 12 * 1 := by linarith
  rw [mul_min_of_nonneg _ _ (by norm_num : (0 : ℝ) ≤ 12)]
  apply le_min hcap'
  rw [mul_min_of_nonneg _ _ (by norm_num : (0 : ℝ) ≤ 12)]
  exact le_min hpoly hfull

/-- The same theorem in the usual exponent `alpha > 1` rather than the
reciprocal exponent `beta = 1 / alpha`. -/
theorem decay_oracle_three_regime
    (err L eta alpha : ℝ) (tail : ℕ → ℝ) (D : ℕ)
    (hD : 1 ≤ D) (hL : 1 ≤ L) (heta : 0 < eta)
    (halpha : 1 < alpha) (hcap : err ≤ 2)
    (horacle : OracleBound err tail (4 * eta) D)
    (htail : ∀ s, 1 ≤ s → s ≤ D →
      tail s ≤ L * (s : ℝ) ^ (1 - alpha))
    (htailD : tail D = 0) :
    err ≤ 12 * min 1
      (min (L ^ alpha⁻¹ * eta ^ ((alpha - 1) / alpha))
        (eta * (D : ℝ))) := by
  have halpha0 : 0 < alpha := lt_trans zero_lt_one halpha
  have hbeta0 : 0 < alpha⁻¹ := inv_pos.mpr halpha0
  have hbeta1 : alpha⁻¹ < 1 := (inv_lt_one₀ halpha0).mpr halpha
  have h := decay_oracle_three_regime_beta err L eta alpha⁻¹ tail D
    hD hL heta hbeta0 hbeta1 hcap horacle (by
      intro s hs1 hsD
      simpa using htail s hs1 hsD) htailD
  rw [polynomialRate_reciprocal L eta alpha halpha0.ne'] at h
  exact h

/-- A selected estimator upper-bounds the fixed-design infimum. -/
theorem fixedDesignRisk_le_selectedEstimator
    {Design Estimator : Type*} [Nonempty Estimator]
    (risk : Design → Estimator → ℝ)
    (hrisk : ∀ design estimator, 0 ≤ risk design estimator)
    (design : Design) (estimator : Estimator) :
    fixedDesignRisk risk design ≤ risk design estimator := by
  unfold fixedDesignRisk
  apply csInf_le
  · refine ⟨0, ?_⟩
    rintro _ ⟨otherEstimator, rfl⟩
    exact hrisk design otherEstimator
  · exact ⟨estimator, rfl⟩

/-- Semantic infimum bridge.  If the risk of one selected estimator really is
the supremum of its pointwise expected errors on a nonempty class, a
pointwise bound proves the corresponding fixed-design minimax upper bound. -/
theorem fixedDesignRisk_le_of_pointwise
    {Design Estimator State : Type*} [Nonempty Estimator]
    (risk : Design → Estimator → ℝ)
    (hrisk : ∀ design estimator, 0 ≤ risk design estimator)
    (design : Design) (estimator : Estimator)
    (states : Set State) (hstates : states.Nonempty)
    (pointRisk : State → ℝ) (bound : ℝ)
    (hsemantic : risk design estimator = sSup (pointRisk '' states))
    (hpointwise : ∀ state ∈ states, pointRisk state ≤ bound) :
    fixedDesignRisk risk design ≤ bound := by
  have hselected : risk design estimator ≤ bound := by
    rw [hsemantic]
    apply csSup_le (hstates.image pointRisk)
    rintro _ ⟨state, hstate, rfl⟩
    exact hpointwise state hstate
  exact (fixedDesignRisk_le_selectedEstimator risk hrisk design estimator).trans
    hselected

/-- Genuine fixed-design decay-class upper theorem.  Its premises are a
semantic expected oracle, the decay envelope, the full-tail identity, and the
loss cap for the exhibited estimator.  The target fixed-design rate is then
derived, rather than passed in as a proposition-valued hypothesis. -/
theorem fixedDesign_decay_upper_of_expected_oracle
    {Design Estimator State : Type*} [Nonempty Estimator]
    (risk : Design → Estimator → ℝ)
    (hrisk : ∀ design estimator, 0 ≤ risk design estimator)
    (design : Design) (estimator : Estimator)
    (states : Set State) (hstates : states.Nonempty)
    (expectedError : State → ℝ) (tail : State → ℕ → ℝ)
    (D : ℕ) (L eta alpha : ℝ)
    (hD : 1 ≤ D) (hL : 1 ≤ L) (heta : 0 < eta)
    (halpha : 1 < alpha)
    (hsemantic : risk design estimator = sSup (expectedError '' states))
    (hcap : ∀ state ∈ states, expectedError state ≤ 2)
    (horacle : ∀ state ∈ states,
      OracleBound (expectedError state) (tail state) (4 * eta) D)
    (htail : ∀ state ∈ states, ∀ s, 1 ≤ s → s ≤ D →
      tail state s ≤ L * (s : ℝ) ^ (1 - alpha))
    (htailD : ∀ state ∈ states, tail state D = 0) :
    fixedDesignRisk risk design ≤ 12 * decayUpperRate D L eta alpha := by
  apply fixedDesignRisk_le_of_pointwise risk hrisk design estimator states
    hstates expectedError _ hsemantic
  intro state hstate
  simpa [decayUpperRate] using
    decay_oracle_three_regime (expectedError state) L eta alpha
      (tail state) D hD hL heta halpha (hcap state hstate)
      (horacle state hstate) (htail state hstate) (htailD state hstate)

/-- The actual worst-case risk on a state class, before taking either design
or estimator infima. -/
noncomputable def classRisk
    {Design Estimator State : Type*} (states : Set State)
    (pointRisk : Design → Estimator → State → ℝ)
    (design : Design) (estimator : Estimator) : ℝ :=
  sSup (pointRisk design estimator '' states)

/-- A nonnegative, bounded pointwise loss has nonnegative worst-case risk. -/
theorem classRisk_nonnegative
    {Design Estimator State : Type*}
    (states : Set State) (hstates : states.Nonempty)
    (pointRisk : Design → Estimator → State → ℝ)
    (hpoint_nonnegative : ∀ design estimator state,
      state ∈ states → 0 ≤ pointRisk design estimator state)
    (hbdd : ∀ design estimator,
      BddAbove (pointRisk design estimator '' states))
    (design : Design) (estimator : Estimator) :
    0 ≤ classRisk states pointRisk design estimator := by
  unfold classRisk
  rcases hstates with ⟨state, hstate⟩
  have hmem : pointRisk design estimator state ∈
      pointRisk design estimator '' states := ⟨state, hstate, rfl⟩
  exact (hpoint_nonnegative design estimator state hstate).trans
    (le_csSup (hbdd design estimator) hmem)

/-- Pointwise control of one explicit estimator controls the fixed-design
minimax risk built from the genuine class supremum and estimator infimum. -/
theorem fixedDesignClassRisk_le_of_pointwise
    {Design Estimator State : Type*} [Nonempty Estimator]
    (states : Set State) (hstates : states.Nonempty)
    (pointRisk : Design → Estimator → State → ℝ)
    (hpoint_nonnegative : ∀ design estimator state,
      state ∈ states → 0 ≤ pointRisk design estimator state)
    (hbdd : ∀ design estimator,
      BddAbove (pointRisk design estimator '' states))
    (design : Design) (estimator : Estimator) (bound : ℝ)
    (hpointwise : ∀ state ∈ states,
      pointRisk design estimator state ≤ bound) :
    fixedDesignRisk (classRisk states pointRisk) design ≤ bound := by
  have hrisk : ∀ design estimator,
      0 ≤ classRisk states pointRisk design estimator :=
    classRisk_nonnegative states hstates pointRisk hpoint_nonnegative hbdd
  apply (fixedDesignRisk_le_selectedEstimator
    (classRisk states pointRisk) hrisk design estimator).trans
  unfold classRisk
  apply csSup_le (hstates.image (pointRisk design estimator))
  rintro _ ⟨state, hstate, rfl⟩
  exact hpointwise state hstate

/-- Fully semantic version of the fixed-design decay upper theorem.  Both
the class supremum and the estimator infimum are definitions; the only
statistical premise is the exhibited estimator's expected oracle. -/
theorem fixedDesignClassRisk_decay_upper_of_expected_oracle
    {Design Estimator State : Type*} [Nonempty Estimator]
    (states : Set State) (hstates : states.Nonempty)
    (pointRisk : Design → Estimator → State → ℝ)
    (hpoint_nonnegative : ∀ design estimator state,
      state ∈ states → 0 ≤ pointRisk design estimator state)
    (hbdd : ∀ design estimator,
      BddAbove (pointRisk design estimator '' states))
    (design : Design) (estimator : Estimator)
    (tail : State → ℕ → ℝ) (D : ℕ) (L eta alpha : ℝ)
    (hD : 1 ≤ D) (hL : 1 ≤ L) (heta : 0 < eta)
    (halpha : 1 < alpha)
    (hcap : ∀ state ∈ states,
      pointRisk design estimator state ≤ 2)
    (horacle : ∀ state ∈ states,
      OracleBound (pointRisk design estimator state)
        (tail state) (4 * eta) D)
    (htail : ∀ state ∈ states, ∀ s, 1 ≤ s → s ≤ D →
      tail state s ≤ L * (s : ℝ) ^ (1 - alpha))
    (htailD : ∀ state ∈ states, tail state D = 0) :
    fixedDesignRisk (classRisk states pointRisk) design ≤
      12 * decayUpperRate D L eta alpha := by
  apply fixedDesignClassRisk_le_of_pointwise states hstates pointRisk
    hpoint_nonnegative hbdd design estimator _
  intro state hstate
  simpa [decayUpperRate] using
    decay_oracle_three_regime
      (pointRisk design estimator state) L eta alpha (tail state) D
      hD hL heta halpha (hcap state hstate) (horacle state hstate)
      (htail state hstate) (htailD state hstate)

/-- Sampling-form corollary with `eta = sqrt(D/T)`, giving exactly the rate
displayed in the statistical theorem. -/
theorem fixedDesignClassRisk_sampling_decay_upper
    {Design Estimator State : Type*} [Nonempty Estimator]
    (states : Set State) (hstates : states.Nonempty)
    (pointRisk : Design → Estimator → State → ℝ)
    (hpoint_nonnegative : ∀ design estimator state,
      state ∈ states → 0 ≤ pointRisk design estimator state)
    (hbdd : ∀ design estimator,
      BddAbove (pointRisk design estimator '' states))
    (design : Design) (estimator : Estimator)
    (tail : State → ℕ → ℝ) (D : ℕ) (T L alpha : ℝ)
    (hD : 1 ≤ D) (hT : 0 < T) (hL : 1 ≤ L)
    (halpha : 1 < alpha)
    (hcap : ∀ state ∈ states,
      pointRisk design estimator state ≤ 2)
    (horacle : ∀ state ∈ states,
      OracleBound (pointRisk design estimator state) (tail state)
        (4 * Real.sqrt ((D : ℝ) / T)) D)
    (htail : ∀ state ∈ states, ∀ s, 1 ≤ s → s ≤ D →
      tail state s ≤ L * (s : ℝ) ^ (1 - alpha))
    (htailD : ∀ state ∈ states, tail state D = 0) :
    fixedDesignRisk (classRisk states pointRisk) design ≤
      12 * samplingDecayRate D T L alpha := by
  have hDpos : 0 < (D : ℝ) := by exact_mod_cast hD
  have heta : 0 < Real.sqrt ((D : ℝ) / T) :=
    Real.sqrt_pos.2 (div_pos hDpos hT)
  have h := fixedDesignClassRisk_decay_upper_of_expected_oracle
    states hstates pointRisk hpoint_nonnegative hbdd design estimator tail
    D L (Real.sqrt ((D : ℝ) / T)) alpha hD hL heta halpha hcap
    horacle htail htailD
  rw [decayUpperRate_sqrt_dimension_div_samples D T L alpha hT
    (lt_trans zero_lt_one halpha).ne'] at h
  exact h

/-- The minimax sandwich with the fixed-design upper input discharged from
an actual expected oracle.  Only the genuinely separate scientific lower
bound remains a premise. -/
theorem decay_minimax_of_expected_oracle
    {Design Estimator State : Type*} [Nonempty Estimator]
    (states : Set State) (hstates : states.Nonempty)
    (pointRisk : Design → Estimator → State → ℝ)
    (hpoint_nonnegative : ∀ design estimator state,
      state ∈ states → 0 ≤ pointRisk design estimator state)
    (hbdd : ∀ design estimator,
      BddAbove (pointRisk design estimator '' states))
    (design : Design) (estimator : Estimator)
    (tail : State → ℕ → ℝ) (D : ℕ) (L eta alpha lowerConstant : ℝ)
    (hD : 1 ≤ D) (hL : 1 ≤ L) (heta : 0 < eta)
    (halpha : 1 < alpha)
    (hcap : ∀ state ∈ states,
      pointRisk design estimator state ≤ 2)
    (horacle : ∀ state ∈ states,
      OracleBound (pointRisk design estimator state)
        (tail state) (4 * eta) D)
    (htail : ∀ state ∈ states, ∀ s, 1 ≤ s → s ≤ D →
      tail state s ≤ L * (s : ℝ) ^ (1 - alpha))
    (htailD : ∀ state ∈ states, tail state D = 0)
    (hlower : lowerConstant * decayUpperRate D L eta alpha ≤
      unrestrictedRisk (classRisk states pointRisk)) :
    (lowerConstant * decayUpperRate D L eta alpha ≤
        unrestrictedRisk (classRisk states pointRisk) ∧
      unrestrictedRisk (classRisk states pointRisk) ≤
        12 * decayUpperRate D L eta alpha) ∧
    (lowerConstant * decayUpperRate D L eta alpha ≤
        fixedDesignRisk (classRisk states pointRisk) design ∧
      fixedDesignRisk (classRisk states pointRisk) design ≤
        12 * decayUpperRate D L eta alpha) := by
  have hrisk : ∀ design estimator,
      0 ≤ classRisk states pointRisk design estimator :=
    classRisk_nonnegative states hstates pointRisk hpoint_nonnegative hbdd
  apply two_experiment_minimax_of_infima
    (classRisk states pointRisk) hrisk design
    (decayUpperRate D L eta alpha) lowerConstant 12 hlower
  exact fixedDesignClassRisk_decay_upper_of_expected_oracle
    states hstates pointRisk hpoint_nonnegative hbdd design estimator tail
    D L eta alpha hD hL heta halpha hcap horacle htail htailD

end TomographyOracleCore
