import TomographyOracleCore.DecayLowerAlgebra
import TomographyOracleCore.DecayHardTail
import TomographyOracleCore.LowerConstants

namespace TomographyOracleCore

/-!
# Admissibility of the hard-family mass

This module connects the manuscript's explicit constant with the already
formalized three-way lower-envelope value.  It proves that the chosen mass
obeys the spectral-ordering, decay-envelope, and information-scale
restrictions.  It still makes no packing, information, Fano, or minimax
assertion.
-/

/-- The paper's mass choice at integer effective rank `m`. -/
noncomputable def hardFamilyMass
    (m : ℕ) (L eta alpha : ℝ) : ℝ :=
  hardFamilyScaleConstant alpha * decayLowerValue m L eta alpha

theorem decayLowerValue_nonnegative
    (m : ℕ) (L eta alpha : ℝ)
    (hL : 0 ≤ L) (heta : 0 ≤ eta) :
    0 ≤ decayLowerValue m L eta alpha := by
  unfold decayLowerValue
  apply le_min (by norm_num)
  apply le_min
  · exact mul_nonneg hL (Real.rpow_nonneg (Nat.cast_nonneg m) _)
  · exact mul_nonneg (Nat.cast_nonneg m) heta

theorem hardFamilyMass_nonnegative
    (m : ℕ) (L eta alpha : ℝ)
    (hL : 0 ≤ L) (heta : 0 ≤ eta) :
    0 ≤ hardFamilyMass m L eta alpha := by
  exact mul_nonneg (hardFamilyScaleConstant_pos alpha).le
    (decayLowerValue_nonnegative m L eta alpha hL heta)

/-- The hard mass is at most `1/4`, hence its two head eigenvalues remain
larger than its individual tail eigenvalues. -/
theorem hardFamilyMass_le_quarter
    (m : ℕ) (L eta alpha : ℝ) :
    hardFamilyMass m L eta alpha ≤ 1 / 4 := by
  have hvalue : decayLowerValue m L eta alpha ≤ 1 :=
    min_le_left _ _
  have hscale : 0 ≤ hardFamilyScaleConstant alpha :=
    (hardFamilyScaleConstant_pos alpha).le
  calc
    hardFamilyMass m L eta alpha ≤ hardFamilyScaleConstant alpha * 1 := by
      exact mul_le_mul_of_nonneg_left hvalue hscale
    _ = hardFamilyScaleConstant alpha := by ring
    _ ≤ 1 / 4 := hardFamilyScaleConstant_le_quarter alpha

/-- The mass satisfies the spectral-decay restriction used by the hard-tail
membership theorem. -/
theorem hardFamilyMass_le_decay_scale
    (m : ℕ) (L eta alpha : ℝ) (hL : 0 ≤ L) :
    hardFamilyMass m L eta alpha ≤
      (2 : ℝ) ^ (1 - alpha) * L * (m : ℝ) ^ (1 - alpha) := by
  let tailScale : ℝ := L * (m : ℝ) ^ (1 - alpha)
  have hvalue : decayLowerValue m L eta alpha ≤ tailScale :=
    (min_le_right _ _).trans (min_le_left _ _)
  have hscale : 0 ≤ hardFamilyScaleConstant alpha :=
    (hardFamilyScaleConstant_pos alpha).le
  have htailScale : 0 ≤ tailScale := by
    exact mul_nonneg hL (Real.rpow_nonneg (Nat.cast_nonneg m) _)
  calc
    hardFamilyMass m L eta alpha ≤
        hardFamilyScaleConstant alpha * tailScale := by
      exact mul_le_mul_of_nonneg_left hvalue hscale
    _ ≤ (2 : ℝ) ^ (1 - alpha) * tailScale := by
      exact mul_le_mul_of_nonneg_right
        (hardFamilyScaleConstant_le_decay alpha) htailScale
    _ = (2 : ℝ) ^ (1 - alpha) * L *
        (m : ℝ) ^ (1 - alpha) := by
      simp only [tailScale]
      ring

/-- The mass satisfies the information restriction `b <= c_I m eta`. -/
theorem hardFamilyMass_le_information_scale
    (m : ℕ) (L eta alpha : ℝ) (heta : 0 ≤ eta) :
    hardFamilyMass m L eta alpha ≤
      lowerInformationConstant * ((m : ℝ) * eta) := by
  let informationScale : ℝ := (m : ℝ) * eta
  have hvalue : decayLowerValue m L eta alpha ≤ informationScale :=
    (min_le_right _ _).trans (min_le_right _ _)
  have hscale : 0 ≤ hardFamilyScaleConstant alpha :=
    (hardFamilyScaleConstant_pos alpha).le
  have hinformationScale : 0 ≤ informationScale :=
    mul_nonneg (Nat.cast_nonneg m) heta
  calc
    hardFamilyMass m L eta alpha ≤
        hardFamilyScaleConstant alpha * informationScale := by
      exact mul_le_mul_of_nonneg_left hvalue hscale
    _ ≤ lowerInformationConstant * informationScale := by
      exact mul_le_mul_of_nonneg_right
        (hardFamilyScaleConstant_le_information alpha) hinformationScale
    _ = lowerInformationConstant * ((m : ℝ) * eta) := by
      rfl

/-- The exact hard tail generated by `hardFamilyMass` belongs to the desired
polynomial envelope for every positive truncation index. -/
theorem hardFamilyMass_tail_decay_membership
    (m : ℕ) (L eta alpha : ℝ)
    (hm : 1 ≤ m) (hL : 1 ≤ L) (heta : 0 ≤ eta)
    (halpha : 1 < alpha) :
    ∀ s : ℕ, 1 ≤ s →
      hardFamilyTail m (hardFamilyMass m L eta alpha) s ≤
        L * (s : ℝ) ^ (1 - alpha) := by
  apply hardFamilyTail_decay_membership m alpha L
    (hardFamilyMass m L eta alpha) hm halpha hL
  · exact hardFamilyMass_nonnegative m L eta alpha
      (le_trans zero_le_one hL) heta
  · exact hardFamilyMass_le_quarter m L eta alpha
  · exact hardFamilyMass_le_decay_scale m L eta alpha
      (le_trans zero_le_one hL)

end TomographyOracleCore
