"""Recheck all prior convergence arrays against independent d,T budgets.

Preserve their old source identity. These are revalidated historical outputs,
not results claimed to have been generated by the corrected solver.
"""
import hashlib
import json
from pathlib import Path
import sys
import time

import numpy as np

ROOT=Path(__file__).resolve().parent.parent
OLD=ROOT.parent/'msi_estimator_audit_2026-09-20'
sys.path.insert(0,str(ROOT/'src'))
from estimators import Channel, mathematical_validation
from run_identity import source_hashes, file_hash
from runtime_io import save_json


def main():
    started=time.perf_counter()
    old_sources={p.name:file_hash(p) for p in (OLD/'src').glob('*.py')}
    manifest=json.loads((OLD/'reports/raw_results_manifest.json').read_text())
    checked_files=set()
    def require_file(path):
        relative=str(path.relative_to(OLD))
        if relative not in checked_files:
            assert file_hash(path)==manifest[relative]['sha256'],relative
            checked_files.add(relative)
    result=dict(status='running',checks=[],failures=[],datasets=0,
                legacy_source_sha256=old_sources,checker_source_sha256=source_hashes(),
                interpretation='Fresh mathematical recheck of historical arrays; no solver rerun.')
    channels={}
    for study in ['convergence_n4','convergence_n8']:
        config=json.loads((OLD/'configs'/ (study+'.json')).read_text())
        config_hash=hashlib.sha256(json.dumps(config,sort_keys=True).encode()).hexdigest()
        for path in sorted((OLD/'results'/study).glob('*/summary.json')):
            require_file(path)
            row=json.loads(path.read_text())
            assert row['status']=='complete'
            assert row['source_sha256']==old_sources
            assert row['config_sha256']==config_hash
            data_path=path.parent/'data.npz';require_file(data_path)
            assert row['data_sha256']==file_hash(data_path)
            with np.load(data_path) as data:
                rho,means,sizes=data['rho'],data['means'],data['sizes']
            case=row['case'];key=(case['n'],case['k'])
            if key not in channels:channels[key]=Channel(*key)
            c=channels[key]
            for T,b in zip(sizes,means):
                estimates=path.parent/('estimates_T%d.npz'%T);require_file(estimates)
                with np.load(estimates) as saved:
                    for method in ['PLS','OMD','MW-PLS']:
                        rec=next(r for r in row['records'] if r['T']==int(T) and r['method']==method)
                        assert rec['mean_sha256']==hashlib.sha256(b.tobytes()).hexdigest()
                        tau=config.get('solver_options',{}).get('tol_factor',1.)
                        assert tau==1.,'Historical eta policy differs at nondefault tolerance.'
                        check=mathematical_validation(c,b,int(T),saved[method.replace('-','_')],method,
                            tol_factor=tau,dual_witness=saved['OMD_dual'] if method=='OMD' and 'OMD_dual' in saved else None,rho=rho)
                        item=dict(study=study,case=case,rep=row['rep'],T=int(T),method=method,validation=check)
                        result['checks'].append(item)
                        if not check['mathematical_checks_passed']:result['failures'].append(item)
                        assert abs(check['trace_norm_error']-rec['validation']['trace_norm_error'])<1e-8
            result['datasets']+=1
            if result['datasets']%10==0:print('RECHECKED',result['datasets'],'datasets',len(result['checks']),'fits',flush=True)
    result.update(status='passed' if not result['failures'] else 'failed',
                  fit_count=len(result['checks']),hashed_files=len(checked_files),seconds=time.perf_counter()-started)
    assert result['datasets']==130 and result['fit_count']==3090
    save_json(ROOT/'reports/legacy_revalidation.json',result)
    print({k:result[k] for k in ['status','datasets','fit_count','hashed_files','seconds']})
    assert not result['failures']


if __name__=='__main__':main()
